baseURL: "ajohnfowler.github.io"
languageCode: "en-us"
title: "Adam Fowler"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Adam Fowler"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/A_Icon.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Adam Fowler" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Adam Fowler."
    subtitle: "Full Stack Developer"
    content: "I do computer stuff ;)"
    image: /images/Avatar.svg
    roundImage: true
    button:
      enable: true
      name: "Resume"
      url: "/resume/Resume - Adam Fowler.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/ajohnfowler
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ajohnfowler/

  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      I’m an experienced full-stack software developer based in Dartmouth, NS. I have worked on various projects during my career including defense contracts, satellite data visualization, and cloud computing solutions utilizing a wide variety of tech stacks.
      
      I’m always striving for personal improvement; continuously exploring new and exciting technologies to expand my computer science and electronics knowledge.
      
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Angular"
        - "Vue"
        - "C++"
        - "Jenkins"
        - "Godot"
        - "Golang"
        - "Docker"
        - "Bash"

  # Experience
  experience:
    enable: true
    items:
      - job: "Intermediate Software Developer"
        company: "MDA Space Ltd"
        companyUrl: "https://mda.space"
        date: "Oct 2021 - Present"
        content: |-
          I am currently working as a Software Developer on a Defense Contract for the Candian Navy.
          
          A previous project involved using statellite data to combat illegal fishing activty at a global scale.

          Responsabilities in this role:
          - Helping onboard new project members
          - Refactoring code into different languages
          - Working with microservice architacture to make scalable solutions
          - Writing automated tests to match code coverage criteria
          - Working closely with a team across time zones to discuss software architecture requirements
          - Set up and maintain CI/CD processes development as well as developing a robust release process


      - job: "Software Developer"
        company: "Ziiware Inc"
        companyUrl: "https://www.ziiware.com"
        date: "Oct 2017 - Oct 2021"
        content: |-
          This role involved improving and maintaining a cloud based mobile wholesale ordering solution for customers across the US.
          
          Responsabilities in this role:
          - Implement new features and maintain a cloud-based order entry and ERP solutions for wholesalers
          - Developing and deploying applications on the  Google Cloud Platform
          - Develop sales analytics visualizations for customers using Google Dataprep and Tableau
          - Communicate with customers in both a support capacity as well as defining solution requirements
          - Mentoring new employees and Co-Op students

  # Education
  education:
    enable: true
    index: false
    items:
      - title: "Bachelor of Computer Science"
        school:
          name: "Acadia University, Wolfville"
          url: "https://www2.acadiau.ca/"
        date: "2017"

  # Projects
  projects:
    title: "Personal Projects"
    enable: true
    items:
      - title: Helldive Randomizer
        content: Website to generate random loadouts for the Helldivers 2 video game
        image: /images/projects/HelldiveRandomizer.png
        badges:
          - "Vue"
          - "Bootstrap"
          - "Typescript"
        links:
          - icon: fa fa-link
            url: https://helldive-randomizer.com/
          - icon: fab fa-github
            url: https://github.com/ajohnfowler/helldive-randomizer

      - title: Nautilus Interactive
        content: Website for my Indie Game Studio
        image: /images/projects/NautilusInteractive.png
        badges:
          - "Hugo"
          - "HTML"
          - "CSS"
          - "YAML"
        links:
          - icon: fa fa-link
            url: https://nautilusinteractive.com/

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:ajohnfowler@gmail.com

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/ajohnfowler
      linkedin: https://www.linkedin.com/in/ajohnfowler/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"